services:
  promocodefactory.webhost:
    image: ${DOCKER_REGISTRY-}promocodefactorywebhost
    build:
      context: .
      dockerfile: PromoCodeFactory.WebHost/Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: HomeworkDockerDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
